language: node_js

node_js:
  - 6.11.5

branches:
  only:
    - staging
    - master

env:
  global:
    # Shippable API token used to trigger deploy
    - secure: UMk2qNCnd/fKqpwCMuJLrAa9uNkNN+QiKpjsBcpYA3+64MFnJ04jMIOHuiMEj6hAaD3790r/ojtMBYmdxnL6sENDBBKMBYRls2W0bdKrrOU6ylHsAWfFIm50x/r+iWRYNMUFDpGIRiiNYDqUcomu1DUvEq/g668aOOD/Q87D+9epxkeCBDTGOJDNYvgIxPkAE+r26iPHnrr2t8Keu+H7mTajSA/wyiF4YguIXi/u+9B+XJOVfhMxZkLdCuC6+qI5+a3OJ5D7wDxEU1AiW2axKqzmb5RenQ/EePJllYvWfJhNLfmdIv4fkIDAoUV8iP/XZ/swmStq+BQFIUl0k8YuzQ==
build:
  ci:
    # Create the version file
    - ./create_version.sh

    # Pull latest image to be used as cache
    - docker pull nrgi/jade-revenues:$BRANCH || echo 'Cache not available'

    # Use the `--cache-from` option to use the latest image in the repo as a cache for this build. Available since Docker 1.13
    # This should speed up the build time.
    - docker build -t nrgi/jade-revenues:$BRANCH.$COMMIT --cache-from nrgi/jade-revenues:$BRANCH .

    # Create the `latest` tag and force it in case the tag is already there from a previous build
    - docker tag nrgi/jade-revenues:$BRANCH.$COMMIT nrgi/jade-revenues:$BRANCH

    - docker push nrgi/jade-revenues:$BRANCH
    - docker push nrgi/jade-revenues:$BRANCH.$COMMIT

    # Trigger deploy through building a repo with deploy configuration
    - ./shippable-deploy.sh
integrations:
  hub:
    - integrationName: nrgiDockerHub
      type: docker
  notifications:
    - integrationName: email
      type: email
      recipients:
        - nrgi@vitaminsoftware.com
      branches:
        only:
          - master
          - staging
      on_success: change
      on_failure: always
